version: '3'
services:
    nginx:
        image: 'linuxserver/letsencrypt:arm64v8-0.35.1-ls37'
        container_name: letsencrypt
        cap_add:
          - NET_ADMIN
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - URL=arm.hatari.org
          - SUBDOMAINS=
          - VALIDATION=http
        volumes:
          - ./config:/config
            #  ports:
           #  port443:443
           #  port80:80 #optional
           #  port10505:10505
        network_mode: "host"
        restart: unless-stopped
